development:
  adapter: mysql2
  enconding: utf8
  host: localhost
  database: companies_development
  username: companies
  password: companies

test:
  adapter: mysql2
  enconding: utf8
  host: localhost
  database: companies_test
  username: companies
  password: companies

production:
  adapter: mysql2
  enconding: utf8
  host: localhost
  database: companies_production
  username: companies
  password: companies

