development:
  adapter: mysql2
  enconding: utf8
  host: localhost
  database: companies_development
  username: companies
  password: companies

test:
  adapter: mysql2
  enconding: utf8
  host: localhost
  database: companies_test
  username: companies
  password: companies

production:
  adapter: mysql2
  enconding: utf8
  host: localhost
  database: companies_production
  username: companies
  password: companies

customers_development:
  adapter: mysql2
  enconding: utf8
  host: localhost
  database: customers_development
  username: customers
  password: customers

customers_test:
  adapter: mysql2
  enconding: utf8
  host: localhost
  database: customers_test
  username: customers
  password: customers

customers_production:
  adapter: mysql2
  enconding: utf8
  host: localhost
  database: customers_production
  username: customers
  password: customers
